[build]
    command = "make build"
    functions = "/functions"

[[redirects]]
    from = "/"
    to = "/.netlify/functions/dynamic-css"

[[redirects]]
    from = "/cors-proxy"
    to = "/.netlify/functions/cors-proxy"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    X-Content-Type-Options = "nosniff"