[build]
  command = "make build"
  functions = "functions"
  publish = "./"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/dynamic-css"

[[redirects]]
  from = "/.netlify/functions/cors-proxy"
  to = "/cors-proxy"