[build]
  command = "make build"
  publish = "./"

[functions]
    directiory = "/functions

[[redirects]]
  from = "/"
  to = "/.netlify/functions/dynamic-css"

[[redirects]]
  from = "/cors-proxy"
  to = "/.netlify/functions/cors-proxy"